### ISSUE TITLE
Web scraping vs local?

### ISSUE THREAD

**Issue by krcm0209** [rwoldberg/ldata-ha#1]
I see that you appear to be logging into the leviton website and scraping the data from the LDATA hub. Have you spent any time trying to intercept the network traffic locally to see if it's possible to reverse engineer it?

**Comment by rwoldberg** [comment]
They don't have an API for the LDATA module, so from what I can gather it is not possible.

**Comment by krcm0209** [comment]
It's definitely not possible in any sanctioned or official capacity, but perhaps someone may come along with Wireshark or whatever and figure it out anyway. I wouldn't want to discount it as impossible just yet.

**Comment by rwoldberg** [comment]
Perhaps, but I would hope the traffic is over SSL.  I was thinking about to trying to create an EPS32 based controller to replace the LDATA but that would snooping on the bluetooth protocol that the LDATA and breakers use to communicate with each other.  But I don't have the hardware for that.  Maybe if there is enough pressure on Leviton they will add a local API to the LDATA module.

**Comment by krcm0209** [comment]
I just emailed loadcentersupport@leviton.com with a local API feature request. I expect absolutely nothing will come of it, but you miss 100% of the shots you don't take.

**Comment by rwoldberg** [comment]
We can hope.
