### ISSUE TITLE
Panel Total Daily Energy is Unknown with LDATA

### ISSUE THREAD

**Issue by d235j** [rwoldberg/ldata-ha#12]
I currently have a first-gen LDATA and the Panel Total Daily Energy is showing as Unknown. This is after several days of operation. Is this expected?

**Comment by infotechjrf** [comment]
I may be wrong but I believe this is kind of normal since the LDATA module is not equipped with the Clamps that reads both Phase A and Phase B like LWHEM module does.

**Comment by d235j** [comment]
In that case, would it make sense for the integration to detect LDATA vs. LWHEM and display only the appropriate properties?

**Comment by rwoldberg** [comment]
Right now the module is just adding all of the energy for each breaker.    My integration is showing values for the panel.  Could you enable debug logging and check the logs and see if there is anything related to LDATA and post it?  Removing any personal information of course.

**Comment by d235j** [comment]
I'm seeing the expected LDATA fetch (full of data) and WHEMS fetch (empty); the data is full of personal information though. Are there any properties I should be looking for (or for the lack of)?

**Comment by rwoldberg** [comment]
I would look for any errors.

**Comment by d235j** [comment]
Right, there are no errors.

**Comment by d235j** [comment]
Of course, now the problem has gone away, and Total Daily Energy is populating. Is this something caused by Debug being disabled initially?

**Comment by rwoldberg** [comment]
Interesting.  I wonder if there was some strange issue with home assistant and that somehow got resolved.  I'll close this ticket but I will look at my code to see if there is anything I can see that might be coded wrong.
