### ISSUE TITLE
Support for Leviton’s Whole Home Energy Monitor (LWHEM-2)

### ISSUE THREAD

**Issue by iSynthetixx** [rwoldberg/ldata-ha#15]
Is it possible to add support for Leviton’s Whole Home Energy Monitor (LWHEM-2)? The LDATA has been discontinued. 

https://www.leviton.com/en/products/lwhem-2

**Comment by danielmbrown603** [comment]
It works with LWHEM-2, go ahead and try it.

**Comment by rwoldberg** [comment]
@iSynthetixx I have already added support.  Install it and it should work just fine, with one exception, I have not yet added support for the CT monitors.
