### ISSUE TITLE
HA reboot and artificial power spike appears

### ISSUE THREAD

**Issue by danielmbrown603** [rwoldberg/ldata-ha#16]
I noticed this during the last ldata update. Since then, I have tried restarting HA a few times over the last few days, and its consistent. During a restart of HA, an artificial power spike appears and usually represents 1/3 to 1/2 of my total daily power usage within a single hour. I have checked all of my individual devices and I do not see any other surges in graphs. Anyone else experiencing this? Thank you

![image](https://github.com/rwoldberg/ldata-ha/assets/79930376/55a2ee64-6c82-4229-9211-755adf7b6fab)

**Comment by rwoldberg** [comment]
@danielmbrown603 I have not noticed this, and I have rebooted my system several times in the last few days.  Could you open the chart for  "Breaker Panel 1 Total Daily Energy" and post a screen shot?

**Comment by danielmbrown603** [comment]
> @danielmbrown603 I have not noticed this, and I have rebooted my system several times in the last few days. Could you open the chart for "Breaker Panel 1 Total Daily Energy" and post a screen shot?

![image](https://github.com/rwoldberg/ldata-ha/assets/79930376/e03ba6a4-41ed-4cb3-88ac-e4daaa19bb25)
![image](https://github.com/rwoldberg/ldata-ha/assets/79930376/f6edda05-12f5-4881-aaed-ade60591ba77)
![image](https://github.com/rwoldberg/ldata-ha/assets/79930376/4f38f86b-c1a5-4c96-877f-2ec08cd5f8a9)

**Comment by rwoldberg** [comment]
Interesting, there is no strange data there, I don't know why the energy tab would be showing such odd behavior, but I don't think it is because of the Ldata integration.   This may be a question for the HA team.

**Comment by danielmbrown603** [comment]
Just for testing, I tried restaring HA again about an hour ago. Maybe this is cumulative, as the spike is much bigger. I know this doesn't narrow it down, just more detail. Thanks

![image](https://github.com/rwoldberg/ldata-ha/assets/79930376/e91f7514-98f6-4d01-85e9-a41af0edfc02)

**Comment by rwoldberg** [comment]
How do you have the energy settings configured? Could you take some screenshots of the /config/energy page?

**Comment by danielmbrown603** [comment]
> How do you have the energy settings configured? Could you take some screenshots of the /config/energy page?

As minimum and basic as can be.

![image](https://github.com/rwoldberg/ldata-ha/assets/79930376/5de490ce-11a8-411a-9697-b73a003d07ac)

![image](https://github.com/rwoldberg/ldata-ha/assets/79930376/dc0ea6c6-fcc7-4cc2-babf-04b4257e29d5)

**Comment by rwoldberg** [comment]
The only thing I see wrong there is the cost setting, I think you should set a static price or do not track costs as the daily energy is not in dollars.

**Comment by rwoldberg** [comment]
Also, the panel total daily energy resets every day, the entity that I use to track total grid consumption never resets. I am not sure if that is causing issues.

**Comment by danielmbrown603** [comment]
> The only thing I see wrong there is the cost setting, I think you should set a static price or do not track costs as the daily energy is not in dollars.

Makes sense, I just changed it.

**Comment by danielmbrown603** [comment]
> Also, the panel total daily energy resets every day, the entity that I use to track total grid consumption never resets. I am not sure if that is causing issues.

Maybe. But I'd expect this issue would be consistent between our setups, and you aren't experiencing this after a reboot.

Are you running the latest version of HA and HACS too?

**Comment by rwoldberg** [comment]
I do not see any spikes but I am not tracking energy via the total daily energy for the panel.  I could try setting up a virtual HA install like that and see if that shows the same issue.

**Comment by danielmbrown603** [comment]
How do you track total daily power? Do you add your individual breakers under 'electric grid > grid consumption'? Basically where I have Break Panel 1, do you have all of your breakers listed there?

**Comment by rwoldberg** [comment]
I have a solar system that integrates in to home assistant that has a grid consumption entity.

**Comment by rwoldberg** [comment]
I think if you use the new consumption sensors for the CT this should not be an issue any longer.

**Comment by kjoconnor** [comment]
I'm seeing this as well, and I think the underlying issue may be that the integration reports 0 during a restart, but it should probably be reporting unavailable instead according to https://community.home-assistant.io/t/energy-dashboard-shows-crazy-and-unrealistic-energy-spike/479252/11

<img width="615" alt="image" src="https://github.com/rwoldberg/ldata-ha/assets/731233/9dcab1c7-5bc2-4665-9f8a-59cbbe8ac720">

**Comment by danielmbrown603** [comment]
V1.1.7 resolved this issue
