### ISSUE TITLE
Breaker Panels Total Daily Energy Issue

### ISSUE THREAD

**Issue by Psycs** [rwoldberg/ldata-ha#17]
Hi,

I've got Two of the Leviton Smart Breaker Panels and I've noticed that the "sensor.breaker_panel_1_total_daily_energy" and "sensor.breaker_panel_2_total_daily_energy" are combing the kWh instead of displaying the total kWh for each individually.

<img width="243" alt="HA Total Daily Usage" src="https://github.com/rwoldberg/ldata-ha/assets/50240236/5e54d402-9d80-4b4b-9840-86a8fc99092f">

**Comment by rwoldberg** [comment]
I just pushed a fix for this.
