### ISSUE TITLE
Information on local API access

### ISSUE THREAD

**Issue by pwsh** [rwoldberg/ldata-ha#18]
No issues, just passing along information

I was able to intercept the data and document the local API. I made a post of the most useful local API functions at [https://community.home-assistant.io/t/leviton-smart-panel-breakers-integration/320819/17](https://community.home-assistant.io/t/leviton-smart-panel-breakers-integration/320819/17)

**Comment by rwoldberg** [comment]
I will take a look, thanks.

**Comment by rwoldberg** [comment]
@pwsh I just tried this with my LDATA module and it will not connect on port 13107.

**Comment by pwsh** [comment]
Did you put in your device ID?

Example http://10.0.0.2:13107/api/residentialBreakerPanels/LDATA-XXXXX-XXXXX-XXXXX/residentialBreakers

**Comment by rwoldberg** [comment]
@pwsh What firmware version is your LDATA?

**Comment by pwsh** [comment]
I think I figured out why yours may not work. There is code to shut down the API when wifi is connected. I hardwired mine in so I could better capture the traffic.

var httpApiAlwaysOn = fjhUtils.getEnvBool('HTTP_API_ALWAYS_ON', false, localDataPath);

Then this code

			case CL.wifiStateText(CL.wifiState.ClientDisconnected):
				if (httpApiAlwaysOn) {
					httpApiServerStart('wifiCheckCurrentState');
				} else {
					httpApiServerStop('wifiCheckCurrentState');
				}

**Comment by rwoldberg** [comment]
Mine is wired to ethernet as well.   Where did this code you posted come from?

**Comment by pwsh** [comment]
Please email me so I can provide that information. I currently have an open vulnerability disclosure relating to this that I don't want public.

**Comment by djcutch** [comment]
I saw this in release notes for lastest lwhem2 update.  but they refuse to send me the real release notes.

**Comment by rwoldberg** [comment]
@djcutch You saw what in the release notes?

**Comment by djcutch** [comment]
Yes I got an update on lwhem2 couple weeks ago and it mention api improvements which was odd to me Sent from my iPhoneOn Mar 4, 2024, at 7:12 PM, Robert ***@***.***> wrote:﻿
@djcutch You saw what in the release notes?

**Comment by rwoldberg** [comment]
Cool.  Hopefully they will enable the local API.  When they do I will update the integration.
