### ISSUE TITLE
Device/Hub Connection Display

### ISSUE THREAD

**Issue by Vynn** [rwoldberg/ldata-ha#2]
Is it possible to grab and display which hub each breaker device is connected to?

We have two sub panels and the integration does a marvelous job of pulling everything, but internal organization is a bit messy with over 50 breaker device entities in our system.

I'm trying to figure out a better way to display the massive quantity of breakers in our Energy Dashboard and the best thing I can come up with is some grouped sensors (probably per-sub-panel), until Home Assistant decides to make some enhancements on their end. Since the LDATA Hub devices generated by the integration only seem to show current branch consumption, not historical period, being able to see which breakers go to which hub from within the integration would be helpful.

**Comment by rwoldberg** [comment]
I could add the breaker panel ID to the extended attributes of each item.  Would that help?

**Comment by Vynn** [comment]
I would think so? If I can pull the panel ID from an attribute I should be able to use that in all sorts of places, considering Leviton isn't futzing with that data on their end and it stays consistent.

The LDATA two hubs themselves were correctly and separately identified.

**Comment by rwoldberg** [comment]
Ok, I'll look in to doing that.

**Comment by rwoldberg** [comment]
I have added the LDATA module serial number to the sensors.   You can update the integration information for the repository in HACS or wait for it to check for updates.
