### ISSUE TITLE
HA restart causes artificial spikes in Energy dashboard

### ISSUE THREAD

**Issue by kjoconnor** [rwoldberg/ldata-ha#21]
Pretty similar to #16 - I think the underlying issue may be that the integration reports `0` during a restart, but it should probably be reporting `unavailable` instead according to https://community.home-assistant.io/t/energy-dashboard-shows-crazy-and-unrealistic-energy-spike/479252/11

<img width="615" alt="image" src="https://github.com/rwoldberg/ldata-ha/assets/731233/9dcab1c7-5bc2-4665-9f8a-59cbbe8ac720">

**Comment by rwoldberg** [comment]
I will try and take a look at this in the next few days.

**Comment by kjoconnor** [comment]
Hey @rwoldberg did you get a chance to check this out? Thanks!

**Comment by rwoldberg** [comment]
Sorry, I haven't, my build machine crashed and I am working on getting a new one setup.

**Comment by rwoldberg** [comment]
I made some changes that hopefully will fix this.  Let me know if it is still an issue.

**Comment by rwoldberg** [comment]
This should be fixed with 1.1.17
