### ISSUE TITLE
No devices or entities found.

### ISSUE THREAD

**Issue by rubinox355** [rwoldberg/ldata-ha#22]
Forgive my cluelessness with this, as I'm unsure if my configuration is compatible with this integration.

I have an LWHEM installed with CTs on my mains, but not a Leviton Breaker panel nor any smart breakers.
I am not absolutely sure if it is LWHEM or LWHEM-2, but in the Leviton app under device health it specifies "LWHEM" and S/N: 1000_002F_A4A0 and LWHEM Firmware: 1.5.12

It is connected to my network via Wi-Fi. I have not closely inspected the unit for an ethernet port since it was installed by my utility company.

In the app & thru the web portal, I am able to accurately view the current consumption of my home:
Power (Watts), Phase A Voltage, Phase B Voltage

I installed the ldata-ha integration and logged in to mylevition account sucessfully as per the documentation however:
The integration shows "No devices or entities"

Am I missing something, or is my setup incompatible?

Thanks for any help.

**Comment by rwoldberg** [comment]
That is a good question.  The devices usually show up via a panel, I am not sure how CTs show up with out one.  If you are willing to send me an invite to your my.leviton.com residence I can probably figure it out.

**Comment by rubinox355** [comment]
"Only residence owners are authorized to add users. Create your own residence to send an invite."

Appears I'm not an "owner" of my residence -- those permissions must be held by my utility company.
...I wonder if factory resetting the LWHEM would allow me to become the owner? Might upset someone behind a desk though.

Otherwise, I don't see any issue providing you with the credentials to the account.
If you'd like to proceed, I can set a temporary password and email you the login.

**Comment by rwoldberg** [comment]
Sure, reset the password and email it to me, you can get my email address from my profile, which I will hide once I get your email.  I will add the account to a virtual instance of home assistant and see if I can get it working.

**Comment by rubinox355** [comment]
Sent! Thanks!

**Comment by rwoldberg** [comment]
I will try to take a look tonight after work.  Thanks.

**Comment by rwoldberg** [comment]
This should be fixed with v1.1.8

**Comment by rwoldberg** [comment]
This should be fixed with v1.1.8

**Comment by rubinox355** [comment]
Thanks for the fix!
Working perfectly now.

**Comment by jasipsw** [comment]
I seem to be having the same issue described above of panels and data not showing up in Home Assistant. I do know that the monitor I have is the LWHEM-2. There are currently two panels installed in the home, each with its own LWHEM. Is there something I can do to figure this out? Happy to share a login if it would help diagnose an issue.

**Comment by rwoldberg** [comment]
@jasipsw Email me a login and I will check this weekend.

**Comment by jasipsw** [comment]
sure thing! your email isn't visible on your profile page at this time

**Comment by rwoldberg** [comment]
@jasipsw  It is now.  I'll disable it when I get your email.

**Comment by jasipsw** [comment]
sent

**Comment by rwoldberg** [comment]
@jasipsw  This should be fixed for you now.

**Comment by jasipsw** [comment]
Thank You!
