### ISSUE TITLE
Frequency and Voltage not Syncing

### ISSUE THREAD

**Issue by bhhome-ericksonfam** [rwoldberg/ldata-ha#23]
So happy to have found your custom integration. Install was easy with my Lwhem. After several weeks of data it seems though that voltage and frequency aren't pulled in on any breaker. Most of the breakers are gen-2. Only a few gen-1 remain from my original ldata install. How can I determine why and resolve? Also, shouldn't a solar input breaker report negative amps and watts? Thank you, in advance.

**Comment by rwoldberg** [comment]
The original LDATA provided frequency and voltage, the LWHEM does not.  I am not sure the breakers actually provide that data and  I need to remove it as I don't believe it is accurate data.  I will try and do that in the next couple of weeks.   I am not sure about the solar input, as I don't a CT that is tagged as solar, the integration just reports what my.levition.com reports about the breakers.
