### ISSUE TITLE
Data Pull/Configuration Issue

### ISSUE THREAD

**Issue by johnsoga** [rwoldberg/ldata-ha#25]
Not sure if there is perhaps an issue with how HA is configured or maybe the data pulled from MyLeviton is just not good, but I don't believe I have anything configured incorrectly, but a lot of things are showing a 0 value

![Screenshot 2024-11-11 at 11 51 06 PM](https://github.com/user-attachments/assets/5687b49e-1f3d-4ed0-86a8-dd587bb8e2bb)

Any thoughts what I could try troubleshooting/checking?

**Comment by rwoldberg** [comment]
What is your setup?  LDATA or LWHEM and do you have any smart breakers?

**Comment by johnsoga** [comment]
I have the LWHEM-2 (not sure if there was a v1 based on the naming) and nope no smart breakers yet. I actually have two LWHEM-2's one one my main panel and one in a sub panel. Does that help?

**Comment by rwoldberg** [comment]
Ok, so the panel amps are calculated by adding all the smart breaker data.  That is why the values are 0.  If I added the CT data to the panel data that would potentially double the power usage.  My panel is filled with smart breakers so adding the CT would effectively double the power usage.   This integration was created when the only monitor was the LDATA and it did not have CT clamps.  I could update it to just duplicate the data from the GRID_POWER CT, but that does get a bit tricky for backward compatibly withe the LDATA.   If you add some smart breakers you will see data show up in Main Panel section.
