### ISSUE TITLE
Possible to turn 2nd gen brekers on?

### ISSUE THREAD

**Issue by tylerdrew47** [rwoldberg/ldata-ha#26]
Would it be Possible to turn 2nd gen brekers on, I can turn them off and everything seems to be working okay but I cant turn them on and the status after turning off doesnt show off although it does in fact turn them off. Turing on with accurate status would be awsome to do my own load sheding in HA. Thanks so much for everything!

**Comment by rwoldberg** [comment]
I'll have to purchase a gen 2 breaker to see how and if this can be implemented.

**Comment by tylerdrew47** [comment]
if you're interested I have a gen 2 breaker you can have it's a 30 amp double pole id love to donate it for the cause

**Comment by rwoldberg** [comment]
That would be great.  I made my email address public on my profile.

**Comment by rwoldberg** [comment]
@tylerdrew47 I replied to your email, yours ended up in my spam folder, so I just thought I would comment here in case the same happened to mine.

**Comment by rwoldberg** [comment]
Remote turn on has now been implemented.

**Comment by tylerdrew47** [comment]
you're a gentleman and a scholar, thanks a ton

**Comment by rwoldberg** [comment]
Let me know if you have any issues. I will put it through more tests as well.
Robert Woldberg

On Dec 15, 2024, at 3:08 PM, tylerdrew47 ***@***.***> wrote:

﻿

you're a gentleman and a scholar, thanks a ton

**Comment by tylerdrew47** [comment]
will do 

Yahoo Mail: Search, Organize, Conquer 
 
  On Sun, Dec 15, 2024 at 14:13, ***@***.***> wrote:   

Let me know if you have any issues. I will put it through more tests as well.
Robert Woldberg

On Dec 15, 2024, at 3:08 PM, tylerdrew47 ***@***.***> wrote:

﻿

you're a gentleman and a scholar, thanks a ton
