### ISSUE TITLE
Unit has Changed

### ISSUE THREAD

**Issue by danielmbrown603** [rwoldberg/ldata-ha#27]
I noticed my energy graphs stopped populating back on Dec 12th. Not sure what triggered that but I saw this. Anyone else expericing this? 
![image](https://github.com/user-attachments/assets/5b85f0e5-393b-4c37-a667-42c928abf04a)

HA
Core 2024.12.3
Frontend 20241127.8

LDATA 1.1.9

**Comment by rwoldberg** [comment]
I don't think I have changed the sensor types in quite awhile, so I am not sure why it would change.  I would just update it, as the import should be in kWh.

**Comment by danielmbrown603** [comment]
Sounds good, will do. 

Interestingly enough, my panel was behind on updates. I updated to the latest and my HA graphs started to work again.
