### ISSUE TITLE
Run integration in read-only mode only

### ISSUE THREAD

**Issue by davidcoulson** [rwoldberg/ldata-ha#5]
Is there an easy way to add an option to the integration so it's essentially 'read only'? I am trying to avoid a situation where someone with the HA app is able to trip a breaker that requires physical intervention to reset it. Having the state of the breaker could be a binary_sensor, but just no ability to trip it through HA.

Thanks for a really great integration - We're all in on the Leviton panels here, so really happy to have visibility into this data in HA!

**Comment by rwoldberg** [comment]
I'll look at adding this.

**Comment by rwoldberg** [comment]
Added a configuration flag for read only mode.
