### ISSUE TITLE
Add Total Daily Consumption to Breaker Panel Device

### ISSUE THREAD

**Issue by MHillyer** [rwoldberg/ldata-ha#7]
First of all, I love this integration, thank you so much, it was the missing piece in my HA puzzle.

I suggest adding a total daily consumption to the breaker panel device, to bring it into alignment with the individual breakers. It would be nice to track daily power draw over time.

**Comment by MHillyer** [comment]
Sorry, I was referring to Total Daily Energy, which is available for all breakers individually but not for the panel itself, which does indeed have the useful total watts and amps.

Mike

**Comment by rwoldberg** [comment]
Oh, I miss-read that.  I will look in to this as well.

**Comment by MHillyer** [comment]
Any update here? I'd like to get each day's consumption home-wide graphed.

**Comment by rwoldberg** [comment]
@MHillyer I have not yet looked at this.  I will try and look at it this weekend.

**Comment by crzykidd** [comment]
Loving this integration, having the total daily kWh for the panel would be a huge plus.

**Comment by rwoldberg** [comment]
Added this in version 1.0.14
