### ISSUE TITLE
Add the word Breaker to every device name

### ISSUE THREAD

**Issue by MHillyer** [rwoldberg/ldata-ha#8]
Loving the integration, ended up with an unintended consequence when I added it without read-only:

Because the names of some of my breakers are the same as the names of some of my rooms/areas in HA, I ended up saying via voice command "Turn off the master bedroom" and the breaker remote tripped. I didn't realize it at the time, since it had the desired effect (all the lights went out), but the next morning was puzzling when nothing would turn on. Fortunately I saw the push notification from the Leviton app, and I've since renamed all my breakers to end with the word Breaker, but if the integration did this by default it should keep people from getting in trouble.

Also, it might be advisable to add to the readme to not put the breakers in the rooms/areas in HA, but instead in a specific Breaker Panel area, since that could also lead to tripping breakers when telling HA to turn off an area.

**Comment by rwoldberg** [comment]
That is a good idea.  I will update the read me and add "breaker" to each device.  I will also make it read only by default.

**Comment by rwoldberg** [comment]
The switches for each breaker now have 'breaker' added to the end of the name.
